# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tunnel_Model.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 516)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLoadTare = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadTare.setGeometry(QtCore.QRect(190, 470, 113, 32))
        self.btnLoadTare.setProperty("toolTipDuration", 4)
        self.btnLoadTare.setObjectName("btnLoadTare")
        self.inpRunName = QtWidgets.QLineEdit(self.centralwidget)
        self.inpRunName.setGeometry(QtCore.QRect(110, 40, 261, 21))
        self.inpRunName.setObjectName("inpRunName")
        self.btnSaveResults = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveResults.setGeometry(QtCore.QRect(450, 460, 113, 32))
        self.btnSaveResults.setDefault(False)
        self.btnSaveResults.setFlat(False)
        self.btnSaveResults.setObjectName("btnSaveResults")
        self.lblRunName = QtWidgets.QLabel(self.centralwidget)
        self.lblRunName.setGeometry(QtCore.QRect(30, 40, 71, 20))
        self.lblRunName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRunName.setObjectName("lblRunName")
        self.lblConfiguration = QtWidgets.QLabel(self.centralwidget)
        self.lblConfiguration.setGeometry(QtCore.QRect(10, 70, 91, 20))
        self.lblConfiguration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblConfiguration.setObjectName("lblConfiguration")
        self.inpConfiguration = QtWidgets.QLineEdit(self.centralwidget)
        self.inpConfiguration.setGeometry(QtCore.QRect(110, 70, 261, 21))
        self.inpConfiguration.setObjectName("inpConfiguration")
        self.lblAirspeed = QtWidgets.QLabel(self.centralwidget)
        self.lblAirspeed.setGeometry(QtCore.QRect(180, 140, 61, 16))
        self.lblAirspeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAirspeed.setObjectName("lblAirspeed")
        self.lblMPHAirspeed = QtWidgets.QLabel(self.centralwidget)
        self.lblMPHAirspeed.setGeometry(QtCore.QRect(310, 150, 31, 16))
        self.lblMPHAirspeed.setObjectName("lblMPHAirspeed")
        self.lblFtPerSecAirspeed = QtWidgets.QLabel(self.centralwidget)
        self.lblFtPerSecAirspeed.setGeometry(QtCore.QRect(310, 190, 41, 16))
        self.lblFtPerSecAirspeed.setObjectName("lblFtPerSecAirspeed")
        self.outSpeedMPH = QtWidgets.QLCDNumber(self.centralwidget)
        self.outSpeedMPH.setGeometry(QtCore.QRect(240, 140, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.outSpeedMPH.setFont(font)
        self.outSpeedMPH.setDigitCount(4)
        self.outSpeedMPH.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.outSpeedMPH.setObjectName("outSpeedMPH")
        self.tblDrag = QtWidgets.QTableWidget(self.centralwidget)
        self.tblDrag.setGeometry(QtCore.QRect(90, 270, 321, 191))
        self.tblDrag.setWordWrap(False)
        self.tblDrag.setRowCount(6)
        self.tblDrag.setColumnCount(3)
        self.tblDrag.setObjectName("tblDrag")
        self.tblDrag.horizontalHeader().setVisible(False)
        self.tblDrag.verticalHeader().setVisible(False)
        self.lblKg = QtWidgets.QLabel(self.centralwidget)
        self.lblKg.setGeometry(QtCore.QRect(110, 250, 61, 16))
        self.lblKg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKg.setObjectName("lblKg")
        self.lblLb = QtWidgets.QLabel(self.centralwidget)
        self.lblLb.setGeometry(QtCore.QRect(210, 250, 61, 16))
        self.lblLb.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLb.setObjectName("lblLb")
        self.lblKgStd = QtWidgets.QLabel(self.centralwidget)
        self.lblKgStd.setGeometry(QtCore.QRect(310, 250, 61, 16))
        self.lblKgStd.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKgStd.setObjectName("lblKgStd")
        self.lblSampleRate = QtWidgets.QLabel(self.centralwidget)
        self.lblSampleRate.setGeometry(QtCore.QRect(440, 60, 81, 20))
        self.lblSampleRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSampleRate.setObjectName("lblSampleRate")
        self.outSpeedFps = QtWidgets.QLCDNumber(self.centralwidget)
        self.outSpeedFps.setGeometry(QtCore.QRect(220, 180, 81, 21))
        self.outSpeedFps.setDigitCount(6)
        self.outSpeedFps.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.outSpeedFps.setObjectName("outSpeedFps")
        self.outSampleRate = QtWidgets.QLCDNumber(self.centralwidget)
        self.outSampleRate.setGeometry(QtCore.QRect(530, 50, 41, 31))
        self.outSampleRate.setDigitCount(3)
        self.outSampleRate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.outSampleRate.setObjectName("outSampleRate")
        self.lblAoA = QtWidgets.QLabel(self.centralwidget)
        self.lblAoA.setGeometry(QtCore.QRect(20, 140, 41, 20))
        self.lblAoA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAoA.setObjectName("lblAoA")
        self.outAoaDeg = QtWidgets.QLCDNumber(self.centralwidget)
        self.outAoaDeg.setGeometry(QtCore.QRect(70, 140, 61, 31))
        self.outAoaDeg.setDigitCount(4)
        self.outAoaDeg.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.outAoaDeg.setObjectName("outAoaDeg")
        self.lblAoADeg = QtWidgets.QLabel(self.centralwidget)
        self.lblAoADeg.setGeometry(QtCore.QRect(140, 150, 31, 16))
        self.lblAoADeg.setObjectName("lblAoADeg")
        self.lblPower = QtWidgets.QLabel(self.centralwidget)
        self.lblPower.setGeometry(QtCore.QRect(400, 240, 41, 20))
        self.lblPower.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPower.setObjectName("lblPower")
        self.outPower = QtWidgets.QLCDNumber(self.centralwidget)
        self.outPower.setGeometry(QtCore.QRect(450, 230, 71, 31))
        self.outPower.setDigitCount(6)
        self.outPower.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.outPower.setObjectName("outPower")
        self.lblWatts = QtWidgets.QLabel(self.centralwidget)
        self.lblWatts.setGeometry(QtCore.QRect(530, 240, 16, 16))
        self.lblWatts.setObjectName("lblWatts")
        self.outAnemometerMPH = QtWidgets.QLCDNumber(self.centralwidget)
        self.outAnemometerMPH.setGeometry(QtCore.QRect(440, 140, 81, 31))
        self.outAnemometerMPH.setDigitCount(4)
        self.outAnemometerMPH.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.outAnemometerMPH.setObjectName("outAnemometerMPH")
        self.lblAnemometer = QtWidgets.QLabel(self.centralwidget)
        self.lblAnemometer.setGeometry(QtCore.QRect(350, 140, 91, 20))
        self.lblAnemometer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAnemometer.setObjectName("lblAnemometer")
        self.lblFtPerSecAnemometer = QtWidgets.QLabel(self.centralwidget)
        self.lblFtPerSecAnemometer.setGeometry(QtCore.QRect(530, 180, 41, 16))
        self.lblFtPerSecAnemometer.setObjectName("lblFtPerSecAnemometer")
        self.outAnemometerFps = QtWidgets.QLCDNumber(self.centralwidget)
        self.outAnemometerFps.setGeometry(QtCore.QRect(430, 180, 91, 21))
        self.outAnemometerFps.setDigitCount(6)
        self.outAnemometerFps.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.outAnemometerFps.setObjectName("outAnemometerFps")
        self.lblMPHAnemometer = QtWidgets.QLabel(self.centralwidget)
        self.lblMPHAnemometer.setGeometry(QtCore.QRect(530, 150, 31, 16))
        self.lblMPHAnemometer.setObjectName("lblMPHAnemometer")
        self.btnCalibrate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalibrate.setGeometry(QtCore.QRect(20, 470, 111, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCalibrate.setFont(font)
        self.btnCalibrate.setProperty("toolTipDuration", 4)
        self.btnCalibrate.setObjectName("btnCalibrate")
        self.lblPerSec = QtWidgets.QLabel(self.centralwidget)
        self.lblPerSec.setGeometry(QtCore.QRect(570, 60, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(13)
        self.lblPerSec.setFont(font)
        self.lblPerSec.setObjectName("lblPerSec")
        self.lblDataDirectory = QtWidgets.QLabel(self.centralwidget)
        self.lblDataDirectory.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.lblDataDirectory.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDataDirectory.setObjectName("lblDataDirectory")
        self.lblDirPath = QtWidgets.QLabel(self.centralwidget)
        self.lblDirPath.setGeometry(QtCore.QRect(110, 20, 401, 20))
        self.lblDirPath.setObjectName("lblDirPath")
        self.inpComments = QtWidgets.QLineEdit(self.centralwidget)
        self.inpComments.setEnabled(True)
        self.inpComments.setGeometry(QtCore.QRect(110, 100, 471, 21))
        self.inpComments.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.inpComments.setObjectName("inpComments")
        self.lblComments = QtWidgets.QLabel(self.centralwidget)
        self.lblComments.setGeometry(QtCore.QRect(10, 100, 91, 20))
        self.lblComments.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblComments.setObjectName("lblComments")
        self.lblSaving = QtWidgets.QLabel(self.centralwidget)
        self.lblSaving.setGeometry(QtCore.QRect(460, 440, 61, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 205, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 205, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 205, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 205, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 205, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 205, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lblSaving.setPalette(palette)
        self.lblSaving.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lblSaving.setObjectName("lblSaving")
        self.lblAoAOffsetDeg = QtWidgets.QLabel(self.centralwidget)
        self.lblAoAOffsetDeg.setGeometry(QtCore.QRect(140, 190, 31, 16))
        self.lblAoAOffsetDeg.setObjectName("lblAoAOffsetDeg")
        self.outAoaOffsetDeg = QtWidgets.QLCDNumber(self.centralwidget)
        self.outAoaOffsetDeg.setGeometry(QtCore.QRect(70, 180, 61, 31))
        self.outAoaOffsetDeg.setDigitCount(4)
        self.outAoaOffsetDeg.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.outAoaOffsetDeg.setObjectName("outAoaOffsetDeg")
        self.lblAoAOffset = QtWidgets.QLabel(self.centralwidget)
        self.lblAoAOffset.setGeometry(QtCore.QRect(20, 180, 41, 20))
        self.lblAoAOffset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAoAOffset.setObjectName("lblAoAOffset")
        self.lblMotor1 = QtWidgets.QLabel(self.centralwidget)
        self.lblMotor1.setGeometry(QtCore.QRect(40, 280, 45, 13))
        self.lblMotor1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMotor1.setObjectName("lblMotor1")
        self.lblMotor2 = QtWidgets.QLabel(self.centralwidget)
        self.lblMotor2.setGeometry(QtCore.QRect(40, 310, 45, 13))
        self.lblMotor2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMotor2.setObjectName("lblMotor2")
        self.lblMotor3 = QtWidgets.QLabel(self.centralwidget)
        self.lblMotor3.setGeometry(QtCore.QRect(40, 340, 45, 13))
        self.lblMotor3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMotor3.setObjectName("lblMotor3")
        self.lblMotor4 = QtWidgets.QLabel(self.centralwidget)
        self.lblMotor4.setGeometry(QtCore.QRect(40, 370, 45, 13))
        self.lblMotor4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMotor4.setObjectName("lblMotor4")
        self.lblMotor5 = QtWidgets.QLabel(self.centralwidget)
        self.lblMotor5.setGeometry(QtCore.QRect(40, 400, 45, 13))
        self.lblMotor5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMotor5.setObjectName("lblMotor5")
        self.lblMotor6 = QtWidgets.QLabel(self.centralwidget)
        self.lblMotor6.setGeometry(QtCore.QRect(40, 430, 45, 13))
        self.lblMotor6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMotor6.setObjectName("lblMotor6")
        self.outAnemometerFps.raise_()
        self.btnLoadTare.raise_()
        self.inpRunName.raise_()
        self.btnSaveResults.raise_()
        self.lblRunName.raise_()
        self.lblConfiguration.raise_()
        self.inpConfiguration.raise_()
        self.lblAirspeed.raise_()
        self.lblMPHAirspeed.raise_()
        self.lblFtPerSecAirspeed.raise_()
        self.outSpeedMPH.raise_()
        self.tblDrag.raise_()
        self.lblKg.raise_()
        self.lblLb.raise_()
        self.lblKgStd.raise_()
        self.lblSampleRate.raise_()
        self.outSpeedFps.raise_()
        self.outSampleRate.raise_()
        self.lblAoA.raise_()
        self.outAoaDeg.raise_()
        self.lblAoADeg.raise_()
        self.lblPower.raise_()
        self.outPower.raise_()
        self.lblWatts.raise_()
        self.outAnemometerMPH.raise_()
        self.lblAnemometer.raise_()
        self.lblFtPerSecAnemometer.raise_()
        self.lblMPHAnemometer.raise_()
        self.btnCalibrate.raise_()
        self.lblPerSec.raise_()
        self.lblDataDirectory.raise_()
        self.lblDirPath.raise_()
        self.inpComments.raise_()
        self.lblComments.raise_()
        self.lblSaving.raise_()
        self.lblAoAOffsetDeg.raise_()
        self.outAoaOffsetDeg.raise_()
        self.lblAoAOffset.raise_()
        self.lblMotor1.raise_()
        self.lblMotor2.raise_()
        self.lblMotor3.raise_()
        self.lblMotor4.raise_()
        self.lblMotor5.raise_()
        self.lblMotor6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wind Tunnel"))
        self.btnLoadTare.setText(_translate("MainWindow", "Set Load Tare"))
        self.btnSaveResults.setText(_translate("MainWindow", "Save Results"))
        self.lblRunName.setText(_translate("MainWindow", "Run Name:"))
        self.lblConfiguration.setText(_translate("MainWindow", "Configuration:"))
        self.lblAirspeed.setText(_translate("MainWindow", "Airspeed:"))
        self.lblMPHAirspeed.setText(_translate("MainWindow", "MPH"))
        self.lblFtPerSecAirspeed.setText(_translate("MainWindow", "ft/sec"))
        self.lblKg.setText(_translate("MainWindow", "Kg"))
        self.lblLb.setText(_translate("MainWindow", "lb"))
        self.lblKgStd.setText(_translate("MainWindow", "sd Kg"))
        self.lblSampleRate.setText(_translate("MainWindow", "Sample Rate:"))
        self.lblAoA.setText(_translate("MainWindow", "AoA:"))
        self.lblAoADeg.setText(_translate("MainWindow", "Deg"))
        self.lblPower.setText(_translate("MainWindow", "Power:"))
        self.lblWatts.setText(_translate("MainWindow", "W"))
        self.lblAnemometer.setText(_translate("MainWindow", "Anemometer:"))
        self.lblFtPerSecAnemometer.setText(_translate("MainWindow", "ft/sec"))
        self.lblMPHAnemometer.setText(_translate("MainWindow", "MPH"))
        self.btnCalibrate.setText(_translate("MainWindow", "Calibrate..."))
        self.lblPerSec.setText(_translate("MainWindow", "/S"))
        self.lblDataDirectory.setText(_translate("MainWindow", "Data Directory:"))
        self.lblDirPath.setText(_translate("MainWindow", "Dir Path"))
        self.lblComments.setText(_translate("MainWindow", "Comments:"))
        self.lblSaving.setText(_translate("MainWindow", "Saving..."))
        self.lblAoAOffsetDeg.setText(_translate("MainWindow", "Deg"))
        self.lblAoAOffset.setText(_translate("MainWindow", "Offset:"))
        self.lblMotor1.setText(_translate("MainWindow", "Motor 1"))
        self.lblMotor2.setText(_translate("MainWindow", "Motor 2"))
        self.lblMotor3.setText(_translate("MainWindow", "Motor 3"))
        self.lblMotor4.setText(_translate("MainWindow", "Motor 4"))
        self.lblMotor5.setText(_translate("MainWindow", "Motor 5"))
        self.lblMotor6.setText(_translate("MainWindow", "Motor 6"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

